#!/usr/bin/env bash
# postBuild script for Binder
# See here: https://mybinder.readthedocs.io/en/latest/using/config_files.html#postbuild-run-code-after-installing-the-environment

# Do not ignore errors silently:
set -e

# Include the scripts in this repo into PATH:
# The repo' content will be placed in the $HOME folder
echo "export PATH=\${HOME}/bin:\${PATH}" >> $HOME/.bash_profile

# Install NLM's Entrez Direct:
# See: 
sh -c "$(curl -fsSL https://ftp.ncbi.nlm.nih.gov/entrez/entrezdirect/install-edirect.sh)"
echo "export PATH=\$HOME/edirect:\$PATH" >> $HOME/.bash_profile

